name: Update SHEN Subscription File

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 */1 * * *' # Runs every hour

jobs:
  update_subscription_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Subscription Aggregator
        run: python config_aggregator.py

      - name: Commit and Push if SHEN_SUB.txt changed
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          # Check if there are changes to commit
          if git diff --quiet SHEN_SUB.txt; then
            echo "No changes to SHEN_SUB.txt. Nothing to commit."
          else
            git add SHEN_SUB.txt
            git commit -m "Update SHEN_SUB.txt with latest configs"
            # Retry push a few times in case of transient issues (e.g. branch protection not allowing direct push immediately)
            for i in 1 2 3; do git push && break || sleep 15; done
          fi
        env:
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          # It has permissions to push to the repository if the Action is running on the default branch
          # or if appropriate permissions are set for PRs/other branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
